### ISSUE TITLE
JSON mode

### ISSUE THREAD

**Issue by ad-si** [scotty-web/scotty#227]
In the default configuration Scotty returns always HTML. E.g.

```yaml
Content-Type: text/html; charset=utf-8
Date: Mon, 25 Feb 2019 14:12:54 GMT
Server: Warp/3.2.26
Transfer-Encoding: chunked

<h1>500 Internal Server Error</h1>
```
There should be an option to run Scotty in a JSON mode where all default responses are JSON. E.g.:

```yaml
Content-Type: application/json; charset=utf-8
Date: Mon, 25 Feb 2019 14:19:36 GMT
Server: Warp/3.2.26
Transfer-Encoding: chunked

{
    "status": 500
    "description": "There was an error while accessing the database"
}
```
