### ISSUE TITLE
Windows 10 Build Fails using Stack resolver lts-16.16 and Scotty 0.11.6

### ISSUE THREAD

**Issue by DouglasBrunner** [scotty-web/scotty#269]
Building Scotty 0.11.6 on Windows fails using Stack resolver lts-16.16 with the below error.

```
regex-posix > Configuring regex-posix-0.96.0.0...
...
regex-posix > error: Wrap.hsc:96:10: fatal error: regex.h: No such file or directory
regex-posix > compilation terminated.
```

The solution for this build error has been documented on the *regex-posix* repository: https://github.com/haskell-hvr/regex-posix/issues/4#issuecomment-610952562

> In Stack, add the following to your stack.yaml:
```
extra-deps:
   - regex-posix-clib-2.7

flags:
   regex-posix:
      _regex-posix-clib: true
```

I thought I'd post this here as GitHub issues are one of the first places people look when facing build issues with a project.
